# the message name or id
- submit_project_ideas:
  #the list of target describes where you want your message to be sent it can be
  # <twitter OR telegram_group OR telegram_channel >
  targets:
    - twitter
  message-en: |
    Hi all,
    You have a project idea you think the Cameroonian community might benefit from ?
    You can submit this idea to the osscameroon community and we can work on it together.
    Click here to submit
    https://shr.cm/b163b5aa
    Join us here https://shr.cm/245ada53
    #CaParleDev
  message-fr: |
    Vous avez une idee de projet utile a la population Cameroonaise ?
    Soumettez votre projet a la communautés osscameroon.
    Soumettez votre projet ici
    https://shr.cm/b163b5aa
    Nous rejoindre https://shr.cm/245ada53
    #CaParleDev
- bash_tutorial:
  targets:
    - twitter
  message-fr: |
    Apprendre Bash par la pratique avec @elhmne
    Grace a ce tutoriel d'introduction https://www.youtube.com/watch?v=k3EivNtvNR4
    #CaParleDev
    #DEVCommunity
- first_contribution:
  targets:
    - telegram_group
    - telegram_channel
    - twitter
  message: |
    Hope you are working on some fun projects.
    In case you don't know what to work on or would like to try something new, you can make your first contribution to an open
    source project.
    This tutorial will help you starting
    https://www.youtube.com/watch?v=F1SG2Zfzn-U&list=PLYfuyzVpgjOSqTcwvb7WGMZrLrEqZl2rB
    #CaParleDev
- promote_camerapps:
  targets:
    - telegram_channel
    - telegram_group
    - twitter
  message-fr: |
    Bonjour à tous et à toutes,
    Découvrez ce catalogue d'applications, de jeux videos et de communautés Camerounaises
    https://camerapps.com
    Rajoutez vous aussi des applications et gagnez des Yotas, en suivant ce tutoriel
    https://shr.cm/0e4523b6
    #CaParleDev

  message-en: |
    Hi folks,
    Checkout this catalogue of applications, videogames and Cameroonian communities
    https://camerapps.com
    You can add your own apps by following this tutorial
    https://shr.cm/0e4523b6
    #CaParleDev
- earn_yotas:
  targets:
    - twitter
    - telegram_channel
  message-en: |
    Contribute to one of osscameroon's open source projects and earn some Yotas for you to spend on our shop.
    To learn more about Yotas check out this video https://www.youtube.com/watch?v=cHLyhYmIFRk
    Find the shop here https://miniyotas.osscameroon.com/shop
    #CaParleDev
  message-fr: |
    Contribuez a un des projets open source de la communauté pour gagner des Yotas, que vous pourrez
    depenser dans notre boutique en ligne.
    Regardez cette video pour en savoir plus https://www.youtube.com/watch?v=cHLyhYmIFRk
    Vous trouverez notre boutique ici https://miniyotas.osscameroon.com/shop
    #CaParleDev
- osscameroon_website_developers:
  targets:
    - twitter
    - telegram_channel
  message-en: |
    Are you looking for developers to help you build your projects ?
    Find the amazing Cameroonian developers on https://osscameroon.com/developers
    #CaParleDev
  message-fr: |
    Vous recherchez des developpeurs pour travailler sur vos projets ?
    Retrouvez les sur https://osscameroon.com/developers
    #CaParleDev
- osscameroon_website_projects:
  targets:
    - twitter
    - telegram_channel
  message-en: |
    Checkout open source projects maintained by Cameroonian developers here https://osscameroon.com/projects
    #CaParleDev
  message-fr: |
    Retrouvez des projets open source developpes par des developpeurs Camerounais ici https://osscameroon.com/projects
    #CaParleDev
- blog_remote_work:
  targets:
    - twitter
    - telegram_channel

  message-en: |
    Please checkout this great article on how to find remote work from Cameroon by @rufusmairo
    https://blog.osscameroon.com/post/articles/remote_work_cameroon
    #CaParleDev
- blog_fish_shell:
  targets:
    - twitter
    - telegram_channel

  message-en: |
    Please checkout this great article on The fish shell by @rufusmairo
    https://blog.osscameroon.com/post/articles/the-fish-shell-is-amazing
    #CaParleDev
- blog_become_a_developer:
  targets:
    - twitter
    - telegram_channel

  message-en: |
    Please checkout this great article on How to become a developer by @Pokam_Armand
    https://blog.osscameroon.com/post/articles/become-a-software-developer
    #CaParleDev
- blog_docker_basic:
  targets:
    - twitter
    - telegram_channel

  message-en: |
    Please checkout this great article on Docker basics by @abdounasser202
    https://blog.osscameroon.com/post/articles/docker-basics-and-commands
    #CaParleDev
- blog_become_a_software_developer:
  targets:
    - twitter
    - telegram_channel

  message-en: |
    Please checkout this great article on How to to become a software developer by @pokam_armand
    https://blog.osscameroon.com/post/articles/become-a-software-developer
    #CaParleDev

- blog_deploy_castlemock_kubernetes_helm:
  targets:
    - twitter
    - telegram_channel

  message-en: |
    Please checkout this great article on castelmock with kubernetes and helm by @blvcktherippa
    https://blog.osscameroon.com/post/articles/deploy_castlemock_kubernetes_helm
    #CaParleDev

- blog_music_while_coding_is_it_worth:
  targets:
    - twitter
    - telegram_channel

  message-en: |
    Please checkout this great article on music and developer by @pokam_armand
    https://blog.osscameroon.com/post/articles/music-while-coding-is-it-worth
    #CaParleDev

- blog_how_to_create_a_hotspot_on_linux:
  targets:
    - twitter
    - telegram_channel

  message-en: |
    Please checkout this great article on how to create a hotspot on linux by @pythonbrad
    https://blog.osscameroon.com/post/articles/how_to_create_a_hotspot_on_linux
    #CaParleDev

- blog_defeating_imposter_syndrome:
  targets:
    - twitter
    - telegram_channel

  message-en: |
    Please checkout this great article on defeating imposter syndrome by @pokam_armand
    https://blog.osscameroon.com/post/articles/old-enemy-impostor-syndrome/
    #CaParleDev

- support_the_community:
  targets:
    - twitter
    - telegram_channel

  message-en: |
    We are building the open source solution Cameroonians need, and we could not
    do it without your support.
    Thank you!
    If you would like to provide us support checkout out our opencollective account
    and leave us a coffee
    https://opencollective.com/osscameroon
    #CaParleDev
- write_a_blog:
  targets:
    - twitter
    - telegram_channel

  message-en: |
    You recently learned something new or built something fun ?
    Share that with the osscameroon community by writing a blog article.
    This issue will help you get started
    https://github.com/osscameroon/osscameroon-blog/issues/22
    #CaParleDev
