---

# the message name or id
- jobsika_contribute:
  #the list of target describes where you want your message to be sent it can be
  # <twitter OR telegram_group OR telegram_channel >
  targets:
    - twitter
    - telegram_channel
    - telegram_group

  message-en: |
    Don't forget to fill in your salary on http://jobsika.cm ğŸ˜ğŸ‰.
    The platform is completely anonymous.
  message-fr: |
    Nâ€™oubliez pas de renseigner votre salaire sur http://jobsika.cm ğŸ˜ğŸ‰.
    La platform est complÃ¨tement anonyme"
    #CaParleDev
